# Generated by Django 4.1.4 on 2022-12-15 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesapi', '0004_alter_usernotes_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernotes',
            unique_together={('title',)},
        ),
    ]
