# Generated by Django 4.1.4 on 2022-12-15 02:00

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('notesapi', '0007_alter_usernotes_unique_together_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usernotes',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='title_unique'),
        ),
    ]
