# Generated by Django 4.1.4 on 2022-12-15 02:03

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('notesapi', '0008_usernotes_title_unique'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usernotes',
            name='title_unique',
        ),
        migrations.AddConstraint(
            model_name='usernotes',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='title'),
        ),
    ]
