# Generated by Django 4.1.4 on 2022-12-15 09:32

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('notesapi', '0011_remove_usernotes_title_alter_usernotes_title'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usernotes',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('title'), name='title'),
        ),
    ]
